const config = {
  conversions: [
    {
      input: "tiles/tilemap-test.aseprite",
      output: "tilemap-test.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/tilemap-test.aseprite",
      output: "tiles/tilemap-test.png",
      outputFolder: "assets/",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/tilemap-test-2.aseprite",
      output: "tilemap-test-2.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/tilemap-planning.aseprite",
      output: "tilemap-planning.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/tilemap-test-2.aseprite",
      output: "tiles/tilemap-test-2.png",
      outputFolder: "assets/",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/tilemap-planning.aseprite",
      output: "tiles/tilemap-planning.png",
      outputFolder: "assets/",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    { input: "tiles/smoke.png", output: "smoke.png" },
    { input: "tiles/water.png", output: "water.png" },
    {
      input: "tiles/tilemap-test-3.aseprite",
      output: "tilemap-test-3.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/tilemap-test-3.aseprite",
      output: "tiles/tilemap-test-3.png",
      outputFolder: "assets/",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "tiles/poi-tokens.aseprite",
      output: "tiles/poi-tokens.png",
      outputFolder: "assets/",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "maps/test-island-16.tmx",
      output: "test-island-16.json",
      executable: "tiled",
      args: "--export-map json --embed-tilesets ${input} ${output}",
    },
    {
      input: "maps/continental.tmx",
      output: "continental.json",
      executable: "tiled",
      args: "--export-map json --embed-tilesets ${input} ${output}",
    },
    {
      input: "maps/coastal.tmx",
      output: "coastal.json",
      executable: "tiled",
      args: "--export-map json --embed-tilesets ${input} ${output}",
    },
    {
      input: "maps/archipelago.tmx",
      output: "archipelago.json",
      executable: "tiled",
      args: "--export-map json --embed-tilesets ${input} ${output}",
    },
    {
      input: "maps/main-menu.tmx",
      output: "main-menu.json",
      executable: "tiled",
      args: "--export-map json --embed-tilesets ${input} ${output}",
    },
    {
      input: "maps/continental-test.tmx",
      output: "continental-test.json",
      executable: "tiled",
      args: "--export-map json --embed-tilesets ${input} ${output}",
    },
    { input: "airplane/martin.png", output: "martin.png" },
    {
      input: "sounds/airplane-propeller-loop.mp3",
      output: "airplane-propeller-loop.mp3",
    },
    {
      input: "airplane/martin_export_no_outline.png",
      output: "martin-sprite.png",
    },
    {
      input: "airplane/martin_pixel_outline.png",
      output: "martin-outline.png",
    },
    {
      input: "canadair-c415/canadair_export_no_outline.png",
      output: "canadair-sprite.png",
    },
    {
      input: "canadair-c415/canadair_pixel_outline.png",
      output: "canadair-outline.png",
    },
    {
      input: "skycrane/skycrane_export.png",
      output: "skycrane-sprite.png",
    },
    {
      input: "skycrane/skycrane_pixel_outline.png",
      output: "skycrane-outline.png",
    },
    { input: "ui/the-wildfires.png", output: "the-wildfires-logo.png" },
    {
      input: "ui/the-wildfires-planes-hud.aseprite",
      output: "planes-hud.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/retardant-particle.aseprite",
      output: "retardant-particle.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/tanks-overlay.aseprite",
      output: "tanks-overlay.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/torque-pin.aseprite",
      output: "torque-pin.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/velocity-pin.aseprite",
      output: "velocity-pin.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/wind-direction-pin.aseprite",
      output: "wind-direction-pin.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/payload-picker.aseprite",
      output: "payload-picker.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/pin.aseprite",
      output: "pin.png",
      executable: "aseprite",
      args: "-b ${input} --scale 2 --sheet ${output}",
    },
    {
      input: "ui/pin-vertical.aseprite",
      output: "pin-vertical.png",
      executable: "aseprite",
      args: "-b ${input} --scale 2 --sheet ${output}",
    },
    {
      input: "ui/key-nine-slice.aseprite",
      output: "key-nine-slice.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/poi-results-nine-slice.aseprite",
      output: "poi-results-nine-slice.png",
      executable: "aseprite",
      args: "-b ${input} --sheet ${output}",
    },
    {
      input: "ui/poi-status-icons.aseprite",
      output: "poi-status-icons.png",
      executable: "aseprite",
      args: "-b ${input} --scale 2 --sheet ${output}",
    },
    {
      input: "ui/poi-tiles-icons.aseprite",
      output: "poi-tiles-icons.png",
      executable: "aseprite",
      args: "-b ${input} --scale 2 --sheet ${output}",
    },
  ],
};

export default config;
