
// This file is auto-generated by vite-plugin-phaser-asset-pack
// Do not edit this file manually

export const RESOURCES = {
  "bg": "bg",
  "logo": "logo",
  "martin": "martin",
  "tilemap-test": "tilemap-test",
  "test-island-16": "test-island-16",
} as const;
