
// This file is auto-generated by vite-plugin-phaser-asset-pack
// Do not edit this file manually

export const RESOURCES = {
  "airplane-propeller-loop": "airplane-propeller-loop",
  "fire-extinguished": "fire-extinguished",
  "fire-loop": "fire-loop",
  "water-loop": "water-loop",
  "canadair-sprite": "canadair-sprite",
  "martin-sprite": "martin-sprite",
  "martin": "martin",
  "skycrane-sprite": "skycrane-sprite",
  "smoke": "smoke",
  "the-wildfires-ui": "the-wildfires-ui",
  "tilemap-test-2": "tilemap-test-2",
  "tilemap-test": "tilemap-test",
  "water-dial": "water-dial",
  "test-island-16": "test-island-16",
} as const;
